### ISSUE TITLE
make vdirsyncer ui compatible with Nextcloud 27

### ISSUE THREAD

**Issue by BiglifeMatt** [Ucar-Solutions/vdirsyncerui#3]
I already moved to 27 before I got a chance to test/use vdirsyncer.  I hope that it can be updated and helps with my syncing issues.  Thanks.

**Comment by doganoo** [comment]
Hi @BiglifeMatt 

we can update to NC27.

what you mean by "syncing issues"?

**Comment by ionty** [comment]
Hi @doganoo , I could need your app with version 27. When could you do the update?

**Comment by doganoo** [comment]
Hi @ionty 

will prepare this and upload to the Nextcloud app store within the next 3 weeks.

**Comment by ionty** [comment]
Any news on this?

**Comment by doganoo** [comment]
I released the changes to the app store.

Can you please verify you can see and install version 0.0.9?

@ionty

**Comment by ionty** [comment]
I can see the new version in the app store and I can install it. Unfortunately after the installation I can no longer open the settings pages, neither the administrative settings nor the personal settings.

From the nextcloud.log:

`{"reqId":"emslQvOsy7DFNJsXZAHi","level":3,"time":"2024-01-19T14:59:51+00:00","remoteAddr":"xx.yy.zz.aa","user":"xxx.yyy","app":"index","method":"GET","url":"/settings/user","message":"Exception thrown: Exception","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","exception":{"Exception":"Exception","Message":"Call to undefined method OCP\\Util::addInitScript() in file '/var/www/html/custom_apps/vdirsyncerui/lib/Settings/Personal/VdirSyncerUISettings.php' line 45","Code":0,`

It would be great if you could have a look after that, thanks!

**Comment by doganoo** [comment]
@ionty 

what version of Nextcloud are you using?

**Comment by ionty** [comment]
I am currently at 27.1.4 changing to 27.1.5 the next days.

**Comment by ionty** [comment]
I upgraded to 27.1.5 now but still the same behaviour.

**Comment by doganoo** [comment]
can you please update to 0.0.17 and let me know?

**Comment by ionty** [comment]
0.0.17 seems to work now, at least there is no error any more when opening the settings page.

Thanks a lot for upgrading to version 27!

**Comment by doganoo** [comment]
@ionty 

great to read. Thank you for using vdirsyncer UI.

please keep in mind that this is still a < 1 version and not fully developed yet. While it does what it does, there can be side effects or edge cases I did not cover yet. In those case, please do not hesitate to open an issue here.

If you like vdirsyncer UI, I would be happy about feedback, a rating on the app store or any other kind of support.
