### ISSUE TITLE
pairing missing

### ISSUE THREAD

**Issue by tknaller** [Ucar-Solutions/vdirsyncerui#8]
hello

thank you for your amazing software!

unfortunately the pairing section is missing from the configuration since i last updated it. `$.post('/apps/vdirsyncerui/personal/add/pair',{configId: 3,referenceConfigId:4})` in the browser dev tools was working fine though :)

**Comment by doganoo** [comment]
Hi @tknaller 

can you describe the problem a bit more in detail? What exactly are you missing?

**Comment by mrjd19811** [comment]
There is no option in the Personal settings to pair the resources.

**Comment by doganoo** [comment]
@mrjd19811 anything suspicious in the logs? can you post them here?

**Comment by tknaller** [comment]
there simply is no option to pair the resources:
![image](https://github.com/Ucar-Solutions/vdirsyncerui/assets/25546953/4351f2ad-a363-415b-bb9f-8426d08401fb)

Nextcloud Hub 7 (28.0.2)
vdirsyncer ui: 0.0.17

**Comment by doganoo** [comment]
@tknaller any logs/errors in the developer tools?

is it possible to have a look together?

**Comment by mrjd19811** [comment]
Nothing in the f12 menu for chrome if thats what you mean.

I'm open to a screen share session.

**Comment by tknaller** [comment]
yeah no error just missing the whole section - only the hidden state is there, no UI for it:
![image](https://github.com/Ucar-Solutions/vdirsyncerui/assets/25546953/ee2a43d6-2f1b-4af5-accd-3fd12b114546)

**Comment by doganoo** [comment]
just published v.0.0.18.

Can you please check whether the pairing section is restored?

**Comment by mrjd19811** [comment]
Can you push it to nextapp?

**Comment by doganoo** [comment]
not sure what you mean by nextapp.

The Nextcloud App Store is the official way of distributing vdirsyncerUI.

Please reach out for custom support

**Comment by mrjd19811** [comment]
Thats what I meant, to the nextcloud appstore, 

I had to fully remove the addon, and reinstall for it to work.

**Comment by tknaller** [comment]
for me it's working now, thank you

had to restart docker container (docker-compose up -d --force-recreate) for the update to go live (some php caching i think)

**Comment by doganoo** [comment]
@tknaller great to here!

@mrjd19811 can you please reach out to arrange a date for a session?

**Comment by doganoo** [comment]
closing this issue as it seems to be fixed.

@mrjd19811 please reach out if you still have issues
